### ISSUE TITLE
Documentation about input data format

### ISSUE THREAD

**Issue by gewitterblitz** [FlexTRKR/PyFLEXTRKR#36]
Hi,

I would like to thank the developers for making PyFLEXTRKR open-source. While the software is really useful for tracking convective cell properties, there are still a few elements about it that make it difficult for the community to use it right away.

If possible, I would like to request the developers to update the documentation or add a tutorial regarding formatting the input data in a way that PyFLEXTRKR likes it. For example, a lot of the demos available in here use TARANIS to create the demo input data. In that case, gridded files created using other Python packages such as PyART won't have all the dimension fields (or the exact names of the dimension fields) that PyFLEXTRKR accepts. 

A step-by-step guide to curating input data would be highly appreciated. This would save the users a lot of time.

Once again, thanks a lot to the developers for putting this out.

**Comment by gewitterblitz** [comment]
Update: I was able to run the cell tracking and plotting scripts for my dataset. Here is the list of steps that worked for me:

1.  **Generating the gridded radar data netcdf files:** PyFLEXTRKR should work fine with the radar grids generated by PyART but there's a minor catch. By default, the PyART grid may not contain the longitude, latitude, and altitude values for each grid point. The user needs to add these fields to the PyART grid object while creating the gridded netcdf file. The field names should be `point_longitude`, `point_latitude`, and `point_altitude`, respectively. The dimension order in each of these fields should be (z,y,x).
>Similarly, the user also needs to add the `point_x`, `point_y`, and `point_z` fields (following the same dimension order as above).
> Another set of variables that will have to be added are the `lat`, `lon`, and `alt` fields. These are singular fields (i.e., no dimension needed) and correspond to the latitude, longitude, and altitude of the radar.

2. **Generating the Terrain_Masking.nc netcdf file:** Use the `/pyflextrkr/make_terrain_rangemask.py` script to generate the terrain masking file suited for the radar grids being used for cell tracking. Before you can run this script, you will need to download the topography (elevation data) file `ETOPO1_Ice_g_gmt4.grd.gz` from this link: https://www.ngdc.noaa.gov/mgg/global/relief/ETOPO1/data/ice_surface/grid_registered/netcdf/ 
Rename the file as `ETOPO1_Ice_g_gmt4.nc` after downloading and then run the python script to obtain the mask terrain output file.

These are the two major hiccups I faced but others may want to add more to this. 

I'll let the repository owner decide if they want to close this or keep it open for further discussion.

**Comment by feng045** [comment]
Hi @gewitterblitz, thank you for the feedback and suggestions to improve the documentations. 

I updated the **UserGuide.md** and added the following section on preparing input radar data for convective cell tracking. I will close this issue for now. 

### Example code to produce Cartesian gridded radar data

An example Python script to map NEXRAD Level 2 data to a Cartesian grid netCDF file using [PyART](https://github.com/ARM-DOE/pyart) is provided in [`/pyflextrkr/grid_radar_pyart.py`](https://github.com/FlexTRKR/PyFLEXTRKR/blob/main/pyflextrkr/grid_radar_pyart.py).

The gridded radar data produced by the example script can be used for convective cell tracking. An example of the data can be downloaded from: [sample NEXRAD radar data](https://portal.nersc.gov/project/m1867/PyFLEXTRKR/sample_data/radar/nexrad_reflectivity1.tar.gz).

Note that the `terrain_file` in the [example radar cell tracking config file](https://github.com/FlexTRKR/PyFLEXTRKR/blob/main/config/config_nexrad500m_example.yml) is **optional**. If `terrain_file` is provided, radar reflectivity data below `surface_elevation + sfc_dz_min` is filtered before calculating composite reflectivity to identify convective cells. This helps to minimize ground clutter and anomalous propagation effects on convective cell identification.

**Generating the Terrain_Masking.nc netcdf file:** Use the [`/pyflextrkr/make_terrain_rangemask.py`](https://github.com/FlexTRKR/PyFLEXTRKR/blob/main/pyflextrkr/make_terrain_rangemask.py) script to generate the terrain masking file suited for the radar grids being used for cell tracking. Before running this script, you will need to download the topography (elevation data) file `ETOPO1_Ice_g_gmt4.grd.gz` from [NOAA](https://www.ngdc.noaa.gov/mgg/global/relief/ETOPO1/data/ice_surface/grid_registered/netcdf/). Rename the file as `ETOPO1_Ice_g_gmt4.nc` after downloading and then run the python script to obtain the mask terrain output file.

**Comment by feng045** [comment]
I will close this issue for now. Feel free to open it again if there are further related questions.
