### ISSUE TITLE
Error with   <<pip install -e .>>

### ISSUE THREAD

**Issue by Invin-Invin** [FlexTRKR/PyFLEXTRKR#67]
Hello,
Thank you for this job.
I try to install the package but I have an issue at this step:
    pip install -e .

<<Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\Donnees_Sat\Tracking_MCS\PyFLEXTRKR\setup.py", line 4, in <module>
          long_description = fh.read()
                             ^^^^^^^^^
        File "C:\Users\RZ\anaconda\envs\flextrkr\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 6025: character maps to <undefined>
      [end of output]>>

Do you know how to debug this error?
Best regards
M.K.

**Comment by feng045** [comment]
Hi, I don't think I've seen this error before and I'm not sure what is wrong with the install. If you start out a fresh install, do you still see this issue? Or have you already resolve this?

**Comment by Invin-Invin** [comment]
> Hi, I don't think I've seen this error before and I'm not sure what is wrong with the install. If you start out a fresh install, do you still see this issue? Or have you already resolve this?

Hi, I have resolve this issue - thank you!
