### ISSUE TITLE
Config File for Generating Monthly Rainmap FIles

### ISSUE THREAD

**Issue by DebjitP1997** [FlexTRKR/PyFLEXTRKR#76]
Hi,
I want to generate monthly rainmap netcdf files. I could see that this needs some config file to run the calc_tbpf_mcs_monthly_rainmap.py code. I could not find the required config file in the config directory. Can you kindly share one so that I can generate the files.

**Comment by feng045** [comment]
Hi,
You should use the same config file where you run your MCS tracking.  The rainmap code searches the directories specified in the config file for the necessary tracking output files.
-Zhe

**Comment by DebjitP1997** [comment]
Thank you for the reply Sir. I will try this and definitely let you know. 
-Debjit

**Comment by DebjitP1997** [comment]
Sir now I am able to run the code and produce the monthly files. Thank you once again for the help.
-Debjit
