### ISSUE TITLE
Tracking did not restart as expected while tracking MCS

### ISSUE THREAD

**Issue by jiligulu-cqs** [FlexTRKR/PyFLEXTRKR#90]
Hi
While tracking MCS, I find that although in Step 1 it can identify the input data has too many missing values, thus omit the time frame (no `cloudid` file generate as expected). But tracking did not restart as expected by the `timegap: 3.1` in config file. As two figures below, the time gap is over 3.1 hours. This tracking is using `demo_mcs_imerg.sh` and `config_imerg_mcs_tbpf_example.yml`, I only change the input file and modify the start&end date. 
Same issue also occur when I delete some input files between start date and  end date, or using sample GPM IMERG Tb+Precipitation data.
![20220908_073000](https://github.com/FlexTRKR/PyFLEXTRKR/assets/162442840/54df4d5d-9e11-46cf-b3ee-b91fa79ab9df)
![20220909_023000](https://github.com/FlexTRKR/PyFLEXTRKR/assets/162442840/c96ccae3-bd7d-4f55-bbd4-d472bd9fcc14)

**Comment by feng045** [comment]
This bug has been fixed in #92, specifically in [this commit](https://github.com/FlexTRKR/PyFLEXTRKR/pull/92/commits/d195a0c28894755d8f468cd89506fd6d657ff42a) that fixed pyflextrkr/gettracks.py.  Please pull the latest version and test it.

**Comment by jiligulu-cqs** [comment]
Thanks, now it works as expected.
