### ISSUE TITLE
Doubt about segregation between Land and Ocean

### ISSUE THREAD

**Issue by DebjitP1997** [FlexTRKR/PyFLEXTRKR#98]
Respected Sir,
In the give examples, you have considered the land_frac_thesh > 0.9 as Land and ocean_frac_thesh <0.1 as Ocean. So are the ones between 0.1 and 0.9 considered to be coastlines?

**Comment by feng045** [comment]
Hi, that's just thresholds we used in our research. You can choose whatever that suite your need.
